### ISSUE TITLE
Quickshare not working from Bookmarklets

### ISSUE THREAD

**Issue by Bibo-Joshi** [ColinShark/YOURLS_tg-quickshare#1]
Hi! Thanks for the cool plugin.
Unfortunately, it doesn't seem to work, when creating a short url through the bookmarklets linked in the `Tools` page. The default twitter and facebook quickshares do work …
Would be happy for a fix, as I've no clue of PHP myself :D

**Comment by ColinShark** [comment]
I had hacked this plugin together from [this repo](https://github.com/TheChicken14/Whatsapp-quickshare). I have no knowledge of PHP myself xD

Can't really help you, sorry.
