### ISSUE TITLE
Links in Text Installation

### ISSUE THREAD

**Issue by tju79** [ColinShark/YOURLS_tg-quickshare#2]
Hello, 
the Links in the Text in the part installation are old. of course i get the files over the offical download - but i would say remove the files or link them to the same target.

**Comment by ColinShark** [comment]
I made this back in early 2019 for myself and last updated it late 2019. I never planned for anyone else to use this, even after this long.

If you want it fixed, feel free to fork this and do it yourself. I should've probably archived this repo long ago.
